title: Warwick Cyber Security Society
discordURL: https://discord.gg/Ys4fr5CMKj
instagramURL: https://www.instagram.com/warwickcybersoc/
twitterURL: https://twitter.com/warwickcybersoc
githubURL: https://www.github.com/warwickcybersoc/
email: contact@warwickcybersoc.com
societyURL: https://www.warwicksu.com/societies-sports/societies/61481/
exec:
  - name: Ana Vijay
    image: ana-pres.png
    role: President
  - name: Oscar Sharpe
    image: oscars.jpg
    role: Secretary
  - name: Ellis Trisk-Grove
    image: ellis.jpg
    role: Treasurer
  - name: George Liddell
    image: george.jpg
    role: Welfare Officer
  - name: Tom Steer
    image: toms.jpg
    role: Technician
  - name: Keerthana Tharuvara Kallottil
    image: ktk.png
    role: Postgrad Officer & Women's Officer
  - name: Rosie Marlton
    image: blank.png
    role: Social Secretary
  - name: Harry Houlberg
    image: blank.png
    role: "Social Secretary"
navbar:
  - name: Home
    link: /
  - name: Events
    link: /events
  - name: Resources
    link: /resources

achievements:
  - title: "#1 - pwnEd2 CTF (2021)"
    year: 2021
  - title: "#1 - HTB x UNI CTF Qualifiers (2021)"
    year: 2021
  - title: "#1 - Veracode The Hacker Games (2021)"
    year: 2021
  - title: "#1 - BAESystems & University of Warwick Computing Society (2021)"
    year: 2021
 
googleCalendarAPIKey: "AIzaSyB4zs2Pj-03aUlL5CHiRwU-PYVZR8glej0"
googleCalendarID: "cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a@group.calendar.google.com"
googleCalendarURL: "https://calendar.google.com/calendar/embed?src=cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a%40group.calendar.google.com&ctz=Europe%2FLondon"

resources:
  - title: "Warwick Cyber Security Society GitHub"
    description: "Our GitHub repository, where we store all of our resources and write-ups."
    link: "https://github.com"

posts:
  - title: "Intake CTF 2023"
    author: "Tom Steer"
    link: "https://tomsteer.com/posts/intakectf/"
