baseURL = "https://society.cyber.warwick.ac.uk"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "WMG Cyber Society"
theme = "cupper-hugo-theme"
#googleAnalytics = "UA-123456789-1"
#disqusShortname = "yourdiscussshortname"
#enableGitInfo = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99.0

[params]
description = "WMG Cyber Society at the University of Warwick"
homeMetaContent = "WMG Cyber Society at the University of Warwick"
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
dateFormat = "Jan 2, 2006"
#codePenUser = "someUser"
#katex = true
#hideHeaderLinks = false
search = true
#showThemeSwitcher = true
#moveFooterToHeader = false
customCss = [
  "css/override-code.css"
]
#customJs = [
#  "js/custom_01.js",
#  "js/custom_02.js"
#]

[menu]

  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.nav]]
  name = "Meet The Team"
  url = "/team/"
  weight = 2.0

  [[menu.nav]]
  name = "Blog Posts"
  url = "/post/"
  weight = 3.0

  [[menu.nav]]
  name = "Report Security Issue"
  url = "/.well-known/security.txt"
  weight = 4.0

  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 5.0

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1.0
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4.0

  [markup.tableOfContents]
  endLevel = 6.0
  startLevel = 2.0
