title: Warwick Cyber Security Society
description: Welcome to the Warwick Cyber Security Society!. We're a friendly and inclusive community centred around our love of Cyber Security.
discordURL: https://discord.gg/Ys4fr5CMKj
instagramURL: https://www.instagram.com/warwickcybersoc/
twitterURL: https://twitter.com/warwickcybersoc
githubURL: https://www.github.com/warwickcybersoc/
email: contact@warwickcybersoc.com
societyURL: https://www.warwicksu.com/societies-sports/societies/61481/
exec:
  - name: Peter Walker
    role: President
  - name: Oscar Topliss
    role: Vice President
  - name: Ellie Baxter
    role: Treasurer
  - name: Oscar Innes
    role: Welfare Officer
  - name: Samuel Kamas
    role: Technician
  - name: Abi Lowrie
    role: Gender Inclusion Officer
  - name: Artem Polovnev
    role: External Communications Officer
  - name: Jamie Madden
    role: Social Secretary
  - name: Tom Slater
    role: Social Secretary
  - name: Samuel Kamas
    role: Marketing Officer
navbar:
  - name: Home
    link: /
  - name: Sponsors
    link: /sponsors
  - name: misc0nfig
    link: /misc0nfig
  - name: Resources
    link: /resources


achievements:
  - title: "#1 - pwnEd6 CTF (2025)"
    year: 2025
  - title: "#2 - pwnEd5 CTF (2024)"
    year: 2024
  - title: "#1 - SAT UK&TR International CTF (2024)"
    year: 2024
  - title: "#1 - pwnEd2 CTF (2021)"
    year: 2021
  - title: "#1 - HTB x UNI CTF Qualifiers (2021)"
    year: 2021
  - title: "#1 - Veracode The Hacker Games (2021)"
    year: 2021
 
googleCalendarAPIKey: "AIzaSyB4zs2Pj-03aUlL5CHiRwU-PYVZR8glej0"
googleCalendarID: "cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a@group.calendar.google.com"
googleCalendarURL: "https://calendar.google.com/calendar/embed?src=cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a%40group.calendar.google.com&ctz=Europe%2FLondon"

resources:
  - title: "Warwick Cyber Security Society GitHub"
    description: "Our GitHub repository, where we store all of our resources and write-ups."
    link: "https://github.com/WarwickCyberSoc"

posts:
  - title: "Intake CTF 2023"
    author: "Tom Steer"
    link: "https://tomsteer.com/posts/intakectf23/"
  - title: "Intake 2023 Writeups"
    author: "Oscar Sharpe"
    link: "https://oscarsharpe.me/posts/intake-writeup"

sponsors:
  - name: "Crowdstrike"
    link: "https://www.crowdstrike.com/en-gb/"
    image: "/images/Crowdstrike_Recolor.png"
    description: "#WeAreCrowdStrike and our mission is to stop breaches. As a global leader in cybersecurity, our team has changed the game. Since our inception in 2011, our market leading cloud-native platform has offered unparalleled protection against the most sophisticated cyberattacks. It combines the most advanced endpoint protection with expert intelligence to pinpoint the adversaries perpetrating the attacks, not just the malware."
  - name: "Interrupt Labs"
    link: "https://www.interruptlabs.co.uk/"
    image: "/images/IL_Logo.png"
    description: "Interrupt Labs is a leading vulnerability research company working on some of the toughest challenges in the industry from popping browsers to exploiting phones and cars. We cover it all with an exceptional team of vulnerability researchers. We are always on the lookout for talented people; whether you are early on in your career, or you already know your way around IDA, we are keen to talk research."

confSponsors:
- name: "Crowdstrike"
  link: "https://www.crowdstrike.com/en-gb/"
  image: "/images/Crowdstrike_Recolor.png"
  description: "#WeAreCrowdStrike and our mission is to stop breaches. As a global leader in cybersecurity, our team has changed the game. Since our inception in 2011, our market leading cloud-native platform has offered unparalleled protection against the most sophisticated cyberattacks. It combines the most advanced endpoint protection with expert intelligence to pinpoint the adversaries perpetrating the attacks, not just the malware."
- name: "Interrupt Labs"
  link: "https://www.interruptlabs.co.uk/"
  image: "/images/IL_Logo.png"
  description: "Interrupt Labs is a leading vulnerability research company working on some of the toughest challenges in the industry from popping browsers to exploiting phones and cars. We cover it all with an exceptional team of vulnerability researchers. We are always on the lookout for talented people; whether you are early on in your career, or you already know your way around IDA, we are keen to talk research."
- name: "Reversec"
  link: "https://reversec.com/"
  image: "/images/reversec_logo.png"
  description: ""

rooms:
  - "Recharge"
  - "IMC 0.02"
  - "IMC 0.04"
  - "IMC 2.46"

timeslots:
  - "10:00"
  - "10:15"
  - "10:30"
  - "10:45"
  - "11:00"
  - "11:15"
  - "11:30"
  - "11:45"
  - "12:00"
  - "12:15"
  - "12:30"
  - "12:45"
  - "13:00"
  - "13:15"
  - "13:30"
  - "13:45"
  - "14:00"
  - "14:15"
  - "14:30"
  - "14:45"
  - "15:00"
  - "15:15"
  - "15:30"
  - "15:45"
  - "16:00"
  - "16:15"
  - "16:30"
  - "16:45"
  - "17:00"


events:
  - room: "Recharge"
    title: "Arrival"
    speaker: ""
    company: ""
    start: "10:00"
    end: "10:45"

  - room: "IMC 0.02"
    title: "Welcome"
    speaker: "Peter Walker"
    company: "Warwick Cyber Security Society"
    start: "10:45"
    end: "11:00"

  - room: "IMC 0.02"
    title: "Unlocking Opportunities: Navigating a Cyber Security Career"
    speaker: "Rebecca Falconer"
    company: "Microsoft"
    start: "11:00"
    end: "12:00"

  - room: "IMC 2.46"
    title: "What's the worst that can happen? The red team mindset at work"
    speaker: "Andrew Peck"
    company: "Loughborough University"
    start: "11:00"
    end: "13:00"

  - room: "IMC 0.02"
    title: '"Open, Sesame!" - unlocking Bluetooth padlocks with polite requests'
    speaker: "Mi≈Çosz Gaczkowski, Alex Pettifer"
    company: "Reversec"
    start: "12:00"
    end: "13:00"

  - room: "IMC 0.04"
    title: "Day in the life of Information Security and Awareness in Warwick"
    speaker: "Esther Eden"
    company: "University of Warwick"
    start: "12:00"
    end: "12:30"

  - room: "Recharge"
    title: "Lunch & Networking"
    speaker: ""
    company: ""
    start: "13:00"
    end: "14:00"
    
  - room: "IMC 0.02"
    title: "Unveiling Dark Pink - An In-Depth Analysis of APAC's Covert APT Threat"
    speaker: "Pol Thill"
    company: ""
    start: "14:00"
    end: "15:00"

  - room: "IMC 0.04"
    title: "The Toilet Seat Conspiracy: An IoT Horror Story"
    speaker: "Paramjeet Singh"
    company: "Vodafone"
    start: "14:00"
    end: "15:00"

  - room: "IMC 2.46"
    title: "Workshop on Incident Response"
    speaker: "Rhodri Davies, Owen Osagie and Drew Goodlad"
    company: "Crowdstrike"
    start: "14:00"
    end: "15:00"
    
  - room: "IMC 0.02"
    title: "The role of DLP in Cyber Security: Protecting your Digital Footprint"
    speaker: "Shuchi Gupta"
    company: "Vodafone"
    start: "15:00"
    end: "16:00"

  - room: "IMC 0.04"
    title: "Questions on my Career Journey"
    speaker: "David Southgate"
    company: "Vodafone"
    start: "15:00"
    end: "16:00"

  - room: "IMC 0.02"
    title: "The Practical Application Of Indirect Prompt Injection Attacks: From Academia to Industry"
    speaker: "David Willis-Owen"
    company: ""
    start: "16:00"
    end: "17:00"

  - room: "IMC 0.04"
    title: "Using the red team mindset: Why we're not (just) security focused IT people"
    speaker: "Andrew Peck"
    company: "Loughborough University"
    start: "16:00"
    end: "16:30"
